// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.jxjxgo.edcenter.domain.cache.encrypteddata

object EncrypteddataProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """ChljYWNoZS9lbmNyeXB0ZWRkYXRhLnByb3RvIscBCg1FbmNyeXB0ZWREYXRhEhYKBnRpY2tldBgBIAEoCVIGdGlja2V0EhIKB
  Ghhc2gYAiABKAlSBGhhc2gSIAoLZW5jcnlwdFR5cGUYAyABKAlSC2VuY3J5cHRUeXBlEh4KCmVuY3J5cHRLZXkYBCABKAlSCmVuY
  3J5cHRLZXkSIAoLZW5jcnlwdERhdGEYBSABKAlSC2VuY3J5cHREYXRhEiYKDmVuY3J5cHRWZXJzaW9uGAYgASgFUg5lbmNyeXB0V
  mVyc2lvbkIiCiBjb20uanhqeGdvLmVkY2VudGVyLmRvbWFpbi5jYWNoZWIGcHJvdG8z"""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
}