// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `Ed.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package RpcEd;

/**
 * Provides type-specific helper functions.
 **/
public final class EdServiceEndpointPrxHelper extends Ice.ObjectPrxHelperBase implements EdServiceEndpointPrx
{
    private static final String __decrypt_name = "decrypt";

    public DecryptResponse decrypt(String traceId, String ticket)
    {
        return decrypt(traceId, ticket, null, false);
    }

    public DecryptResponse decrypt(String traceId, String ticket, java.util.Map<String, String> __ctx)
    {
        return decrypt(traceId, ticket, __ctx, true);
    }

    private DecryptResponse decrypt(String traceId, String ticket, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__decrypt_name);
        return end_decrypt(begin_decrypt(traceId, ticket, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_decrypt(String traceId, String ticket)
    {
        return begin_decrypt(traceId, ticket, null, false, false, null);
    }

    public Ice.AsyncResult begin_decrypt(String traceId, String ticket, java.util.Map<String, String> __ctx)
    {
        return begin_decrypt(traceId, ticket, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_decrypt(String traceId, String ticket, Ice.Callback __cb)
    {
        return begin_decrypt(traceId, ticket, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_decrypt(String traceId, String ticket, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_decrypt(traceId, ticket, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_decrypt(String traceId, String ticket, Callback_EdServiceEndpoint_decrypt __cb)
    {
        return begin_decrypt(traceId, ticket, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_decrypt(String traceId, String ticket, java.util.Map<String, String> __ctx, Callback_EdServiceEndpoint_decrypt __cb)
    {
        return begin_decrypt(traceId, ticket, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_decrypt(String traceId, 
                                         String ticket, 
                                         IceInternal.Functional_GenericCallback1<DecryptResponse> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_decrypt(traceId, ticket, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_decrypt(String traceId, 
                                         String ticket, 
                                         IceInternal.Functional_GenericCallback1<DecryptResponse> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_decrypt(traceId, ticket, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_decrypt(String traceId, 
                                         String ticket, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_GenericCallback1<DecryptResponse> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_decrypt(traceId, ticket, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_decrypt(String traceId, 
                                         String ticket, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_GenericCallback1<DecryptResponse> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_decrypt(traceId, ticket, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_decrypt(String traceId, 
                                          String ticket, 
                                          java.util.Map<String, String> __ctx, 
                                          boolean __explicitCtx, 
                                          boolean __synchronous, 
                                          IceInternal.Functional_GenericCallback1<DecryptResponse> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_decrypt(traceId, ticket, __ctx, __explicitCtx, __synchronous, 
                             new IceInternal.Functional_TwowayCallbackArg1<DecryptResponse>(__responseCb, __exceptionCb, __sentCb)
                                 {
                                     public final void __completed(Ice.AsyncResult __result)
                                     {
                                         EdServiceEndpointPrxHelper.__decrypt_completed(this, __result);
                                     }
                                 });
    }

    private Ice.AsyncResult begin_decrypt(String traceId, 
                                          String ticket, 
                                          java.util.Map<String, String> __ctx, 
                                          boolean __explicitCtx, 
                                          boolean __synchronous, 
                                          IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__decrypt_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__decrypt_name, __cb);
        try
        {
            __result.prepare(__decrypt_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(traceId);
            __os.writeString(ticket);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public DecryptResponse end_decrypt(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __decrypt_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            DecryptResponseHolder __ret = new DecryptResponseHolder();
            __is.readObject(__ret);
            __is.readPendingObjects();
            __result.endReadParams();
            return __ret.value;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __decrypt_completed(Ice.TwowayCallbackArg1<DecryptResponse> __cb, Ice.AsyncResult __result)
    {
        EdServiceEndpointPrx __proxy = (EdServiceEndpointPrx)__result.getProxy();
        DecryptResponse __ret = null;
        try
        {
            __ret = __proxy.end_decrypt(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    private static final String __encrypt_name = "encrypt";

    public EncryptResponse encrypt(String traceId, String raw)
    {
        return encrypt(traceId, raw, null, false);
    }

    public EncryptResponse encrypt(String traceId, String raw, java.util.Map<String, String> __ctx)
    {
        return encrypt(traceId, raw, __ctx, true);
    }

    private EncryptResponse encrypt(String traceId, String raw, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__encrypt_name);
        return end_encrypt(begin_encrypt(traceId, raw, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_encrypt(String traceId, String raw)
    {
        return begin_encrypt(traceId, raw, null, false, false, null);
    }

    public Ice.AsyncResult begin_encrypt(String traceId, String raw, java.util.Map<String, String> __ctx)
    {
        return begin_encrypt(traceId, raw, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_encrypt(String traceId, String raw, Ice.Callback __cb)
    {
        return begin_encrypt(traceId, raw, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_encrypt(String traceId, String raw, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_encrypt(traceId, raw, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_encrypt(String traceId, String raw, Callback_EdServiceEndpoint_encrypt __cb)
    {
        return begin_encrypt(traceId, raw, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_encrypt(String traceId, String raw, java.util.Map<String, String> __ctx, Callback_EdServiceEndpoint_encrypt __cb)
    {
        return begin_encrypt(traceId, raw, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_encrypt(String traceId, 
                                         String raw, 
                                         IceInternal.Functional_GenericCallback1<EncryptResponse> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_encrypt(traceId, raw, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_encrypt(String traceId, 
                                         String raw, 
                                         IceInternal.Functional_GenericCallback1<EncryptResponse> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_encrypt(traceId, raw, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_encrypt(String traceId, 
                                         String raw, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_GenericCallback1<EncryptResponse> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_encrypt(traceId, raw, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_encrypt(String traceId, 
                                         String raw, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_GenericCallback1<EncryptResponse> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_encrypt(traceId, raw, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_encrypt(String traceId, 
                                          String raw, 
                                          java.util.Map<String, String> __ctx, 
                                          boolean __explicitCtx, 
                                          boolean __synchronous, 
                                          IceInternal.Functional_GenericCallback1<EncryptResponse> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_encrypt(traceId, raw, __ctx, __explicitCtx, __synchronous, 
                             new IceInternal.Functional_TwowayCallbackArg1<RpcEd.EncryptResponse>(__responseCb, __exceptionCb, __sentCb)
                                 {
                                     public final void __completed(Ice.AsyncResult __result)
                                     {
                                         EdServiceEndpointPrxHelper.__encrypt_completed(this, __result);
                                     }
                                 });
    }

    private Ice.AsyncResult begin_encrypt(String traceId, 
                                          String raw, 
                                          java.util.Map<String, String> __ctx, 
                                          boolean __explicitCtx, 
                                          boolean __synchronous, 
                                          IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__encrypt_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__encrypt_name, __cb);
        try
        {
            __result.prepare(__encrypt_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(traceId);
            __os.writeString(raw);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public EncryptResponse end_encrypt(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __encrypt_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            EncryptResponseHolder __ret = new EncryptResponseHolder();
            __is.readObject(__ret);
            __is.readPendingObjects();
            __result.endReadParams();
            return __ret.value;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __encrypt_completed(Ice.TwowayCallbackArg1<EncryptResponse> __cb, Ice.AsyncResult __result)
    {
        EdServiceEndpointPrx __proxy = (EdServiceEndpointPrx)__result.getProxy();
        EncryptResponse __ret = null;
        try
        {
            __ret = __proxy.end_encrypt(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static EdServiceEndpointPrx checkedCast(Ice.ObjectPrx __obj)
    {
        return checkedCastImpl(__obj, ice_staticId(), EdServiceEndpointPrx.class, EdServiceEndpointPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static EdServiceEndpointPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __ctx, ice_staticId(), EdServiceEndpointPrx.class, EdServiceEndpointPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static EdServiceEndpointPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return checkedCastImpl(__obj, __facet, ice_staticId(), EdServiceEndpointPrx.class, EdServiceEndpointPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static EdServiceEndpointPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __facet, __ctx, ice_staticId(), EdServiceEndpointPrx.class, EdServiceEndpointPrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @return A proxy for this type.
     **/
    public static EdServiceEndpointPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        return uncheckedCastImpl(__obj, EdServiceEndpointPrx.class, EdServiceEndpointPrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    public static EdServiceEndpointPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return uncheckedCastImpl(__obj, __facet, EdServiceEndpointPrx.class, EdServiceEndpointPrxHelper.class);
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::RpcEd::EdServiceEndpoint"
    };

    /**
     * Provides the Slice type ID of this type.
     * @return The Slice type ID.
     **/
    public static String ice_staticId()
    {
        return __ids[1];
    }

    public static void __write(IceInternal.BasicStream __os, EdServiceEndpointPrx v)
    {
        __os.writeProxy(v);
    }

    public static EdServiceEndpointPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            EdServiceEndpointPrxHelper result = new EdServiceEndpointPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
